# Generated by Django 5.1.3 on 2024-12-05 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_management', '0002_userprofile_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('units_consumed', models.FloatField()),
                ('rate_per_unit', models.FloatField()),
                ('amount', models.FloatField()),
                ('tax', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid_management.userprofile')),
            ],
        ),
    ]
