# Generated by Django 5.1.3 on 2024-12-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_management', '0003_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customer_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
